apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  ports:
    - name: {{ .Values.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.deployment.name }}
  type: ClusterIP
